### ISSUE TITLE
Cannot figure out how to remove black sidebar

### ISSUE THREAD

**Issue by cjrobe** [ThemeFuse/Scratch-Theme#8] opened 2015-04-09 23:44 UTC
No sidebars are defined and even if I comment out sidebar.php, it still shows the black sidebar.  Any help is appreciated. Thanks so much for the great framework!

**Comment by llemurya** [comment] 2015-04-10 06:26
@cjrobe I don't understand what you mean when say black sidebar ,please give me some screenshots and describe in steps how to reproduce your bug or question. At the first, please read our documentation about how to configure [sidebars](http://manual.unyson.io/en/latest/extension/sidebars/index.html?highlight=sidebars), if it didn't help , give me a full description of your problem and I will help you. I am waiting for your response.

**Comment by cjrobe** [comment] 2015-04-10 11:53
Here's what I mean:
![scratch-black-sidebar](https://cloud.githubusercontent.com/assets/5606066/7087192/7d72a03a-df56-11e4-813c-cd21c26af9d4.png)

When there's no sidebars, it's still there. When I add a left sidebar, it goes on the black space on the left.

I'm sorry, I did read it but I don't really understand. I guess Unyson is over my head.

**Comment by llemurya** [comment] 2015-04-14 07:35
@cjrobe the problem is not in Unyson and not in sidebars, the problem is in .css, please see this [screenshot](http://static.md/8d0abcd9bce62f9ce39dbd3a81fd8bd4#). If you try to integrate a WordPress theme then make your html in order to be full screen then no sidebars.Hope this helps. I close this issue because this is not a Unyson bug.

**Closed by llemurya** 2015-04-14 07:35 UTC

**Comment by exelexys** [comment] 2015-09-03 00:59
So, if the Scratch Theme (child) is selected, how can it be made full-width to eliminate the black area on the left side of the screen? Perhaps this isn't possible with this theme?

Also, in the Scratch Theme, how something like the search button be removed from the header?

Thanks in advance
